### ISSUE TITLE
Implement Conversation Tracker API

### ISSUE THREAD

**Issue by THeK3nger** [Helvia/rasa-kotlin#1]
Implement the Conversation Tracker APIs as specified [here](http://rasa.com/docs/rasa/api/http-api/#tag/Tracker/paths/~1conversations~1{conversation_id}~1tracker/get)

- [x] Retrieve a conversations tracker
- [x] Append an event to a tracker
- [x] Replace a trackers events
- [x] Retrieve an end-to-end story corresponding to a conversation
- [x] Run an action in a conversation
- [x] Predict the next action
- [x] Add a message to a tracker
